### PR TITLE
Error logging to file added.

### LINKED ISSUE #41: Next phase of development - Nov. 2019
- Round Training - make round always be selected - currently after adding new exercises its deselected. Make it possible to change sequence number (redni broj) of trainings.

- Add logging of exceptions - record all such logged errors for later review.

### PR DESCRIPTION
**Pull request by PerAsperaAdAstra3**
When working with circular trainings small issues is fixed, now round stay selected/highlighted after a batch of exercises is added to it. Checked the sequence number editing/changing, it is working.

Added logging for errors - all logs are stored in file to home.user in file TreningLog.log .

Closes #41

### CODE REVIEW

File: src/main/java/training/controller/TrainingController.java [hunk 1]
```diff
@@ -211,7 +222,9 @@ public String createCircularTraining(Model model, @PathVariable String clientId)
 		model.addAttribute("circularYN", true);
 		
 	} catch(Exception e) {
-		e.printStackTrace();  //TODO add logging in future PR.
+		logger.error(e.getMessage());
+		logger.error(LoggingUtil.LoggingMethod(e));
+		e.printStackTrace();
```
Comment (renatav) [inline src/main/java/training/controller/TrainingController.java]: printStackTrace left

File: src/main/java/training/controller/TrainingController.java [hunk 2]
```diff
@@ -260,6 +273,8 @@ public String saveTraining(Model model, @ModelAttribute("trainingDTO") TrainingD
 	try {	
 		 id = saveOrEditTraining(trainingDTO , mode);
 	} catch(Exception e) {
+		logger.error(e.getMessage());
+		logger.error(LoggingUtil.LoggingMethod(e));
 		e.printStackTrace();
 		List<String> messageList = new ArrayList<>();
```
Comment (renatav) [inline src/main/java/training/controller/TrainingController.java]: If there is special error printing implemented here, would it make sense to write that to a file?

File: src/main/java/training/controller/TrainingController.java [hunk 3]
```diff
@@ -327,15 +344,15 @@ public String addExerciseInRound(Model model,
...
+			ExerciseInRound exerciseInRound = exerciseInRoundService.delete(Long.parseLong(exerciseInRoundId));
+			redir.addFlashAttribute("selectedRoundId", exerciseInRound.getRound().getId());
 		} catch(Exception e) {
-				e.printStackTrace();
-				List<String> messageList = new ArrayList<>();
-				StackTraceElement[] trace = e.getStackTrace();
-				for(int i=0; i < trace.length; i++ ) {
+			logger.error(e.getMessage());
+			logger.error(LoggingUtil.LoggingMethod(e));
+			e.printStackTrace();
```
Comment (renatav) [inline src/main/java/training/controller/TrainingController.java]: Same here, also printStackTrace left

File: src/main/java/training/util/LoggingUtil.java [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+	public static String LoggingMethod(Exception e) {
+		StringBuilder build = new StringBuilder();
+		StackTraceElement[] trace = e.getStackTrace();
+		for(StackTraceElement traceTemp : trace) {
+			build.append("\n");
+			build.append(traceTemp.toString());
+		}
+		return build.toString();
+	}
+}
```
Comment (renatav) [inline src/main/java/training/util/LoggingUtil.java]: New line at the end of file missing

File: src/main/java/training/util/PdfGenaratorUtil.java [hunk 5]
```diff
@@ -60,13 +67,18 @@ public int createPdf(String templateName, Map map) throws Exception {
 	            renderer.createPDF(os, false);
 	            renderer.finishPDF();
 	        }catch (IOException e) {
+				logger.error(e.getMessage());
```
Comment (renatav) [inline src/main/java/training/util/PdfGenaratorUtil.java]: Indentation

File: src/main/java/training/util/PdfGenaratorUtil.java [hunk 6]
```diff
@@ -60,13 +67,18 @@ public int createPdf(String templateName, Map map) throws Exception {
...
+				logger.error(LoggingUtil.LoggingMethod(e));
 	           isThereError = 1;
 	        }
 	        finally {
 	            if (os != null) {
 	                try {
 	                    os.close();
-	                } catch (IOException e) { /*ignore*/ }
+	                } catch (IOException e) {
+	        			logger.error(e.getMessage());
```
Comment (renatav) [inline src/main/java/training/util/PdfGenaratorUtil.java]: Indentation

File: src/main/resources/application.properties [hunk 7]
```diff
@@ -18,4 +18,10 @@ spring.thymeleaf.cache=false
 welcome.message=Hello Training
 error.message=Error detected!
 
+# Logging
 
+logging.level.root=info
+
+logging.path=${user.home}
+logging.file=${logging.path}/TreningLog.log
+logging.pattern.file=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n
```
Comment (renatav) [inline src/main/resources/application.properties]: Missing new line at the end of file

File: src/main/java/training/controller/TrainingController.java (hunk 2 above)
Comment (PerAsperaAdAstra3) [reply src/main/java/training/controller/TrainingController.java]: Yes, this was a temporary solution for an issue we had, this is intended to be replaced with correct Spring exception handling so it will be removed in a future updates.
